name: Jira Issue Update
description: Update fields of specific Jira issue
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  issue:
    description: Key of the issue to be transitioned
    required: true
  payload:
    description: The update payload data to send
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
